### ISSUE TITLE
Google Sign-In Returns to SignInActivity

### ISSUE THREAD

**Issue by yagmur2** [i077/CWRUMapper#13]
Sign-in result should connect to a separate activity (PlaceHolder in my code; Itinerary Screen in the final product), but instead closes and returns to same screen. #3

**Comment by i077** [comment]
I tried fixing this by using tasks as specified [here](https://developers.google.com/identity/sign-in/android/sign-in), but it turns out signing in is actually failing with an API exception, code 12500.

See fb255216bf55f911965d14d8cce65b0778a72a9f.

**Comment by i077** [comment]
Signing in seems to work? Only on my laptop, though, @yagmur2 should test on his.

**Comment by i077** [comment]
Might be an issue with emulators, so I'm going to close this for now.
